# Generated by Django 3.2.12 on 2022-05-29 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0208_auto_20220214_1632'),
        ('pretix_eth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('signature', models.CharField(max_length=132)),
                ('raw_message', models.CharField(max_length=256)),
                ('sender_address', models.CharField(max_length=42)),
                ('recipient_address', models.CharField(max_length=42)),
                ('chain_id', models.SmallIntegerField()),
                ('order_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_messages', to='pretixbase.orderpayment')),
            ],
        ),
        migrations.DeleteModel(
            name='WalletAddress',
        ),
    ]
