# Generated by Django 2.1.7 on 2019-02-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_eth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencedethereumobject',
            name='reference',
            field=models.CharField(db_index=True, max_length=190, unique=True),
        ),
    ]
