# Generated by Django 3.2.12 on 2022-07-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_eth', '0004_alter_signedmessage_raw_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signedmessage',
            name='chain_id',
            field=models.IntegerField(),
        ),
    ]
