# Generated by Django 3.2.12 on 2022-09-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pretix_eth', '0006_auto_20220716_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='signedmessage',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
