# Generated by Django 5.2.13 on 2026-04-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_eth', '0009_auto_20230627_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='WCPaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tx_hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('quote_id', models.CharField(db_index=True, max_length=32)),
                ('order_code', models.CharField(max_length=16)),
                ('payer', models.CharField(max_length=42)),
                ('chain_id', models.IntegerField()),
                ('state', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='signedmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
