# Generated by Django 5.2.13 on 2026-04-15 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_eth', '0010_wcpaymentattempt_alter_signedmessage_id'),
        ('pretixbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='X402PendingOrder',
            fields=[
                ('payment_reference', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('order_data', models.JSONField()),
                ('total_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('intended_payer', models.CharField(max_length=42)),
                ('expected_eth_amount_wei_by_chain', models.JSONField(null=True)),
                ('expected_chain_id', models.IntegerField(null=True)),
                ('metadata', models.JSONField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x402_pending_orders', to='pretixbase.event')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'expires_at'], name='pretix_eth__event_i_cd828d_idx')],
            },
        ),
    ]
