# Generated by Django 5.2.13 on 2026-04-15 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_eth', '0011_x402pendingorder'),
        ('pretixbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='X402CompletedOrder',
            fields=[
                ('payment_reference', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tx_hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('pretix_order_code', models.CharField(db_index=True, max_length=16)),
                ('payer', models.CharField(max_length=42)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('chain_id', models.IntegerField()),
                ('total_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('token_symbol', models.CharField(max_length=20)),
                ('crypto_amount', models.CharField(max_length=50, null=True)),
                ('gas_cost_wei', models.CharField(max_length=50, null=True)),
                ('refund_status', models.CharField(db_index=True, max_length=16, null=True)),
                ('refund_tx_hash', models.CharField(max_length=66, null=True)),
                ('refund_meta', models.JSONField(default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x402_completed_orders', to='pretixbase.event')),
            ],
            options={
                'indexes': [models.Index(fields=['event', '-completed_at'], name='pretix_eth__event_i_1459cc_idx'), models.Index(fields=['event', 'refund_status'], name='pretix_eth__event_i_b85da7_idx')],
            },
        ),
    ]
