# Generated by Django 5.2.13 on 2026-04-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_eth', '0012_x402completedorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='X402VerifyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
